-- Database Schema DDL for SecApp
-- Automatically generated from database schema dictionary

BEGIN;

CREATE TABLE IF NOT EXISTS companies (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255),
    slug VARCHAR(255),
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS customer_companies (
    id SERIAL PRIMARY KEY,
    company_id INTEGER,
    name VARCHAR(255),
    code VARCHAR(255),
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (company_id, name),
    FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS propiedades (
    id_propiedad SERIAL PRIMARY KEY,
    nombre VARCHAR(255),
    descripcion TEXT,
    direccion VARCHAR(255),
    activa BOOLEAN DEFAULT TRUE,
    creado_en TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    customer_company_id INTEGER,
    latitude NUMERIC,
    longitude NUMERIC,
    FOREIGN KEY (customer_company_id) REFERENCES customer_companies(id)
);

CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    password_hash VARCHAR(255),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    name VARCHAR(255),
    phone_number VARCHAR(255),
    email VARCHAR(255),
    is_admin BOOLEAN DEFAULT FALSE,
    is_active BOOLEAN DEFAULT TRUE,
    company_id INTEGER,
    is_super_admin BOOLEAN DEFAULT FALSE,
    force_password_change BOOLEAN DEFAULT FALSE,
    updated_at TIMESTAMPTZ,
    FOREIGN KEY (company_id) REFERENCES companies(id)
);

CREATE TABLE IF NOT EXISTS authorized_emails (
    id SERIAL PRIMARY KEY,
    email VARCHAR(255),
    authorized_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    authorized_by VARCHAR(255),
    is_active BOOLEAN DEFAULT TRUE,
    notes TEXT,
    is_admin BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (company_id) REFERENCES companies(id)
);

CREATE TABLE IF NOT EXISTS kpi_thresholds (
    key VARCHAR(255) PRIMARY KEY,
    value NUMERIC,
    updated_at TIMESTAMPTZ,
    updated_by TEXT,
    text_value TEXT
);

CREATE TABLE IF NOT EXISTS password_reset_tokens (
    id SERIAL PRIMARY KEY,
    email VARCHAR(255),
    token_hash VARCHAR(255),
    expires_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS saved_filters (
    id SERIAL PRIMARY KEY,
    user_email VARCHAR(255),
    name VARCHAR(255),
    filters JSONB,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS capacitacion_asistencia (
    id SERIAL PRIMARY KEY,
    session_token VARCHAR(255),
    nombre TEXT,
    cargo VARCHAR(255),
    documento VARCHAR(255),
    firma TEXT,
    creado_en TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    numero_empleado TEXT
);

CREATE TABLE IF NOT EXISTS reportes_incidentes (
    id_reporte_incidente SERIAL PRIMARY KEY,
    cliente_instalacion VARCHAR(255),
    puesto_area_especifica VARCHAR(255),
    fecha_hora TIMESTAMPTZ,
    rol_aplicador VARCHAR(255),
    turno VARCHAR(255),
    nombre_responsable VARCHAR(255),
    firma_responsable TEXT,
    categoria VARCHAR(255),
    tipo_incidente VARCHAR(255),
    descripcion_incidente TEXT,
    nivel_severidad VARCHAR(255),
    impacto VARCHAR(255),
    tiempo_resolucion_min INTEGER,
    responsable_asignado VARCHAR(255),
    estado VARCHAR(255),
    user_email VARCHAR(255),
    creado_en TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    id_propiedad INTEGER,
    foto_evidencia_url TEXT,
    descripcion_impacto TEXT,
    company_id INTEGER,
    customer_company_id INTEGER,
    latitude NUMERIC,
    longitude NUMERIC,
    location_accuracy NUMERIC,
    numero_empleado VARCHAR(255),
    razon_ausentismo VARCHAR(255),
    cubre_puesto VARCHAR(255),
    nombre_persona_cubre VARCHAR(255),
    numero_empleado_cubre VARCHAR(255),
    plan_accion TEXT,
    nombre_responsable_plan VARCHAR(255),
    fecha_cumplimiento_plan DATE,
    estado_seguimiento_plan VARCHAR(255),
    accion_seguimiento TEXT,
    reportado_autoridades VARCHAR(255),
    numero_reporte_autoridades TEXT,
    submitter_timezone TEXT,
    FOREIGN KEY (company_id) REFERENCES companies(id),
    FOREIGN KEY (customer_company_id) REFERENCES customer_companies(id),
    FOREIGN KEY (id_propiedad) REFERENCES propiedades(id_propiedad)
);

CREATE TABLE IF NOT EXISTS reportes_incidentes_personas (
    id SERIAL PRIMARY KEY,
    id_reporte_incidente INTEGER,
    persona_tipo VARCHAR(255),
    persona_nombre TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id_reporte_incidente) REFERENCES reportes_incidentes(id_reporte_incidente) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS supervision_puesto (
    id_supervision SERIAL PRIMARY KEY,
    fecha_hora TIMESTAMPTZ,
    supervisor VARCHAR(255),
    nombre_guardia VARCHAR(255),
    documento_guardia VARCHAR(255),
    serie_arma VARCHAR(255),
    cantidad_municion VARCHAR(255),
    realiza_induccion VARCHAR(255),
    asistencia_puntualidad VARCHAR(255),
    presentacion_uniforme VARCHAR(255),
    estado_limpieza_puesto VARCHAR(255),
    equipamiento_completo VARCHAR(255),
    estado_bitacora VARCHAR(255),
    observaciones_novedades TEXT,
    submitted_by_email VARCHAR(255),
    creado_en TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    firma_supervisor TEXT,
    rol_aplicador VARCHAR(255),
    firma_guardia TEXT,
    foto_evidencia_url TEXT,
    conoce_ordenes_consignas VARCHAR(255),
    horario_detalles_claros VARCHAR(255),
    nombre_guardia_firma VARCHAR(255),
    detalles_puestos TEXT,
    porta_arma TEXT,
    numero_empleado TEXT,
    company_id INTEGER,
    customer_company_id INTEGER,
    id_propiedad INTEGER,
    latitude NUMERIC,
    longitude NUMERIC,
    location_accuracy NUMERIC,
    tipo_arma VARCHAR(255),
    fecha_vencimiento_permiso_porte DATE,
    fecha_ultimo_mtto_arma DATE,
    radio_asignado_serial VARCHAR(255),
    marca_radio VARCHAR(255),
    tipo_radio VARCHAR(255),
    tiempo_en_puesto VARCHAR(255),
    fecha_ultimo_mtto_radio DATE,
    hora_entrada VARCHAR(255),
    hora_salida VARCHAR(255),
    licencia_portar_arma VARCHAR(255),
    matricula_arma VARCHAR(255),
    cliente_instalacion VARCHAR(255),
    submitter_timezone TEXT,
    horario_servicio VARCHAR(255),
    tipo_servicio VARCHAR(255),
    problemas_uniforme TEXT,
    FOREIGN KEY (company_id) REFERENCES companies(id),
    FOREIGN KEY (customer_company_id) REFERENCES customer_companies(id),
    FOREIGN KEY (id_propiedad) REFERENCES propiedades(id_propiedad)
);

CREATE TABLE IF NOT EXISTS medicion_experiencia_cliente (
    id_encuesta SERIAL PRIMARY KEY,
    calificacion_global_nps INTEGER,
    recomendaria_servicio VARCHAR(255),
    observaciones_cliente TEXT,
    submitted_by_email VARCHAR(255),
    creado_en TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    firma_usuario TEXT,
    cliente_instalacion VARCHAR(255),
    fecha_hora TIMESTAMPTZ,
    rol_aplicador VARCHAR(255),
    nombre_responsable VARCHAR(255),
    categoria_evaluada VARCHAR(255),
    encuestado VARCHAR(255),
    firma_encuestado TEXT,
    firma_responsable TEXT,
    atencion_cliente INTEGER,
    comunicacion INTEGER,
    confiabilidad INTEGER,
    capacidad_reaccion INTEGER,
    cumplimiento INTEGER,
    competencia_personal INTEGER,
    actitud_servicio INTEGER,
    atencion_quejas INTEGER,
    company_id INTEGER,
    customer_company_id INTEGER,
    id_propiedad INTEGER,
    latitude NUMERIC,
    longitude NUMERIC,
    location_accuracy NUMERIC,
    submitter_timezone TEXT,
    FOREIGN KEY (company_id) REFERENCES companies(id),
    FOREIGN KEY (customer_company_id) REFERENCES customer_companies(id),
    FOREIGN KEY (id_propiedad) REFERENCES propiedades(id_propiedad)
);

CREATE TABLE IF NOT EXISTS log_de_patrullas (
    id_patrulla SERIAL PRIMARY KEY,
    id_guardia_nombre_guardia VARCHAR(255),
    sitio_ubicacion VARCHAR(255),
    id_patrulla_consecutivo VARCHAR(255),
    fecha DATE,
    hora_inicio TIME,
    hora_fin TIME,
    detalles_incidente TEXT,
    riesgo_detectado VARCHAR(255),
    nivel_riesgo VARCHAR(255),
    estado_patrulla VARCHAR(255),
    contexto_observaciones TEXT,
    firma_guardia TEXT,
    firma_supervisor TEXT,
    submitted_by_email VARCHAR(255),
    creado_en TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    company_id INTEGER,
    customer_company_id INTEGER,
    id_propiedad INTEGER,
    submitter_timezone TEXT,
    FOREIGN KEY (company_id) REFERENCES companies(id),
    FOREIGN KEY (customer_company_id) REFERENCES customer_companies(id),
    FOREIGN KEY (id_propiedad) REFERENCES propiedades(id_propiedad)
);

CREATE TABLE IF NOT EXISTS informe_novedades_disciplinario (
    id_informe SERIAL PRIMARY KEY,
    nombre_responsable VARCHAR(255),
    realizado_por_cargo VARCHAR(255),
    dirigido_a VARCHAR(255),
    empleado_nombre VARCHAR(255),
    empleado_documento VARCHAR(255),
    empleado_cargo VARCHAR(255),
    cliente_instalacion VARCHAR(255),
    puesto_area_especifica VARCHAR(255),
    tipo_novedad TEXT,
    sitio_ocurrencia TEXT,
    descripcion_novedad TEXT,
    otras_personas_involucradas TEXT,
    anexos TEXT,
    submitted_by_email VARCHAR(255),
    creado_en TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    firma_responsable TEXT,
    firma_recibido_revisado TEXT,
    fecha_hora TIMESTAMPTZ,
    rol_aplicador VARCHAR(255),
    turno VARCHAR(255),
    recibido_revisado_por_nombre VARCHAR(255),
    recibido_revisado_por_cargo VARCHAR(255),
    empleado_numero TEXT,
    nombre_testigo TEXT,
    firma_testigo TEXT,
    empleado_niega_firmar BOOLEAN,
    company_id INTEGER,
    customer_company_id INTEGER,
    id_propiedad INTEGER,
    latitude NUMERIC,
    longitude NUMERIC,
    location_accuracy NUMERIC,
    submitter_timezone TEXT,
    FOREIGN KEY (company_id) REFERENCES companies(id),
    FOREIGN KEY (customer_company_id) REFERENCES customer_companies(id),
    FOREIGN KEY (id_propiedad) REFERENCES propiedades(id_propiedad)
);

CREATE TABLE IF NOT EXISTS registro_de_capacitaciones (
    id_capacitacion SERIAL PRIMARY KEY,
    cliente_instalacion VARCHAR(255),
    puesto_area_especifica VARCHAR(255),
    fecha_hora TIMESTAMPTZ,
    rol_aplicador VARCHAR(255),
    turno VARCHAR(255),
    nombre_responsable VARCHAR(255),
    firma_responsable TEXT,
    nombre_capacitacion VARCHAR(255),
    objetivo_capacitacion TEXT,
    observaciones_retroalimentacion TEXT,
    lista_asistencia JSONB,
    practica_simulacro_realizado VARCHAR(255),
    nivel_comprension VARCHAR(255),
    recomendaciones TEXT,
    submitted_by_email VARCHAR(255),
    creado_en TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    company_id INTEGER,
    customer_company_id INTEGER,
    id_propiedad INTEGER,
    foto_evidencia_url TEXT,
    submitter_timezone TEXT,
    FOREIGN KEY (company_id) REFERENCES companies(id),
    FOREIGN KEY (customer_company_id) REFERENCES customer_companies(id),
    FOREIGN KEY (id_propiedad) REFERENCES propiedades(id_propiedad)
);

CREATE TABLE IF NOT EXISTS registro_y_acta_de_visita (
    id_visita SERIAL PRIMARY KEY,
    cliente_instalacion VARCHAR(255),
    puesto_area_especifica VARCHAR(255),
    fecha_hora TIMESTAMPTZ,
    rol_aplicador VARCHAR(255),
    turno VARCHAR(255),
    visita_realizada_por VARCHAR(255),
    firma_visitante TEXT,
    motivo_visita TEXT,
    objetivo_reunion TEXT,
    actividades_realizadas TEXT,
    satisfaccion_cliente VARCHAR(255),
    comentarios_satisfaccion TEXT,
    persona_atendio VARCHAR(255),
    cargo_atendio VARCHAR(255),
    telefono_contacto VARCHAR(255),
    submitted_by_email VARCHAR(255),
    creado_en TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    detalles_participantes TEXT,
    nombre_visitante TEXT,
    cargo_visitante TEXT,
    temas_tratados TEXT,
    acuerdos_compromisos TEXT,
    nombre_responsable TEXT,
    fecha_cumplimiento DATE,
    company_id INTEGER,
    customer_company_id INTEGER,
    id_propiedad INTEGER,
    compromisos_estados TEXT,
    latitude NUMERIC,
    longitude NUMERIC,
    location_accuracy NUMERIC,
    submitter_timezone TEXT,
    estado VARCHAR(255),
    FOREIGN KEY (company_id) REFERENCES companies(id),
    FOREIGN KEY (customer_company_id) REFERENCES customer_companies(id),
    FOREIGN KEY (id_propiedad) REFERENCES propiedades(id_propiedad)
);

CREATE TABLE IF NOT EXISTS planilla_vehicular (
    id_planilla_vehicular SERIAL PRIMARY KEY,
    cliente_instalacion VARCHAR(255),
    puesto_area_especifica VARCHAR(255),
    fecha_hora TIMESTAMPTZ,
    rol_aplicador VARCHAR(255),
    turno VARCHAR(255),
    nombre_responsable VARCHAR(255),
    firma_responsable TEXT,
    placa_vehiculo VARCHAR(255),
    kilometraje_entrega INTEGER,
    kilometraje_salida INTEGER,
    estado_rines VARCHAR(255),
    juego_senales_carretera VARCHAR(255),
    gato_hidraulico VARCHAR(255),
    palanca_gato VARCHAR(255),
    estado_asientos VARCHAR(255),
    estado_tapetes_alfombras VARCHAR(255),
    limpieza_carroceria VARCHAR(255),
    luces_delanteras VARCHAR(255),
    luces_direccionales VARCHAR(255),
    luces_traseras VARCHAR(255),
    parabrisas_delantero VARCHAR(255),
    parabrisas_trasero VARCHAR(255),
    defensa_delantera VARCHAR(255),
    defensa_trasera VARCHAR(255),
    puertas_vidrios VARCHAR(255),
    tapa_radiador VARCHAR(255),
    tapa_aceite_motor VARCHAR(255),
    bateria_tapa VARCHAR(255),
    espejo_retrovisor_interno VARCHAR(255),
    espejos_retrovisores_externos VARCHAR(255),
    limpia_brisas VARCHAR(255),
    antena_radio VARCHAR(255),
    radio_funciona VARCHAR(255),
    llanta_repuesto VARCHAR(255),
    aire_acondicionado VARCHAR(255),
    diagrama_danos TEXT,
    novedades_criticas TEXT,
    accion_inmediata TEXT,
    firma_entrega TEXT,
    firma_recibe TEXT,
    oficial_operaciones_nombre VARCHAR(255),
    oficial_operaciones_firma TEXT,
    submitted_by_email VARCHAR(255),
    creado_en TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    kilometraje_vehiculo INTEGER,
    company_id INTEGER,
    customer_company_id INTEGER,
    id_propiedad INTEGER,
    numero_empleado VARCHAR(255),
    fecha_ultimo_mantenimiento DATE,
    submitter_timezone TEXT,
    FOREIGN KEY (company_id) REFERENCES companies(id),
    FOREIGN KEY (customer_company_id) REFERENCES customer_companies(id),
    FOREIGN KEY (id_propiedad) REFERENCES propiedades(id_propiedad)
);

CREATE TABLE IF NOT EXISTS planilla_motocicletas (
    id SERIAL PRIMARY KEY,
    cliente_instalacion VARCHAR(255),
    puesto_area_especifica VARCHAR(255),
    fecha_hora TIMESTAMPTZ,
    rol_aplicador VARCHAR(255),
    turno VARCHAR(255),
    placa_motocicleta VARCHAR(255),
    kilometraje_entrega INTEGER,
    kilometraje_salida INTEGER,
    estado_neumaticos VARCHAR(255),
    estado_rines VARCHAR(255),
    equipo_carretera VARCHAR(255),
    estado_kit_arrastre VARCHAR(255),
    estado_palanca_soporte VARCHAR(255),
    estado_forro_asiento VARCHAR(255),
    estado_tapas_derecha VARCHAR(255),
    estado_luces_direccionales_derecha VARCHAR(255),
    estado_luces_delanteras VARCHAR(255),
    estado_guarda_fango_delantero VARCHAR(255),
    estado_sistema_freno_delantero VARCHAR(255),
    estado_manillar_embrague VARCHAR(255),
    estado_manillar_freno_delantero VARCHAR(255),
    estado_manometros_indicadores VARCHAR(255),
    estado_tanque_combustible VARCHAR(255),
    tapa_tanque_combustible VARCHAR(255),
    espejos_retrovisores VARCHAR(255),
    tapa_aceite_motor VARCHAR(255),
    bateria_tapa VARCHAR(255),
    estado_luces_izquierda VARCHAR(255),
    estado_luces_direccionales_izquierda VARCHAR(255),
    estado_luz_trasera VARCHAR(255),
    estado_guarda_fango_trasero VARCHAR(255),
    estado_tubo_escape VARCHAR(255),
    estado_palanca_freno VARCHAR(255),
    estado_palanca_cambios VARCHAR(255),
    novedades_criticas_detectadas TEXT,
    accion_inmediata_tomada TEXT,
    firma_entrega TEXT,
    firma_recibe TEXT,
    submitted_by_email VARCHAR(255),
    creado_en TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    nombre_responsable VARCHAR(255),
    firma_responsable TEXT,
    oficial_operaciones_nombre VARCHAR(255),
    oficial_operaciones_firma TEXT,
    kilometraje_motocicleta INTEGER,
    company_id INTEGER,
    customer_company_id INTEGER,
    id_propiedad INTEGER,
    numero_empleado VARCHAR(255),
    fecha_ultimo_mantenimiento DATE,
    submitter_timezone TEXT,
    FOREIGN KEY (company_id) REFERENCES companies(id),
    FOREIGN KEY (customer_company_id) REFERENCES customer_companies(id),
    FOREIGN KEY (id_propiedad) REFERENCES propiedades(id_propiedad)
);

CREATE TABLE IF NOT EXISTS checklist_cumplimiento (
    id SERIAL PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    submitted_by_email VARCHAR(255),
    cliente_instalacion VARCHAR(255),
    puesto_area_especifica VARCHAR(255),
    fecha_hora TIMESTAMPTZ,
    turno VARCHAR(255),
    nombre_auditor VARCHAR(255),
    firma_auditor TEXT,
    rol_aplicador VARCHAR(255),
    agente_nombre_completo VARCHAR(255),
    agente_tipo_documento VARCHAR(255),
    agente_numero_documento VARCHAR(255),
    agente_cargo_rol VARCHAR(255),
    agente_puesto VARCHAR(255),
    curso_certificacion VARCHAR(255),
    academia_certifica VARCHAR(255),
    nro_resolucion VARCHAR(255),
    fecha_resolucion DATE,
    vigencia_desde DATE,
    vigencia_hasta DATE,
    evidencia_url TEXT,
    nivel_cumplimiento VARCHAR(255),
    copia_certificados_fisica VARCHAR(255),
    certificados_cargados_sistema VARCHAR(255),
    documentacion_coincide_hv VARCHAR(255),
    fechas_vigentes VARCHAR(255),
    firma_guarda_supervisado TEXT,
    company_id INTEGER,
    customer_company_id INTEGER,
    id_propiedad INTEGER,
    agente_numero_empleado VARCHAR(255),
    submitter_timezone TEXT,
    FOREIGN KEY (company_id) REFERENCES companies(id),
    FOREIGN KEY (customer_company_id) REFERENCES customer_companies(id),
    FOREIGN KEY (id_propiedad) REFERENCES propiedades(id_propiedad)
);

CREATE TABLE IF NOT EXISTS confiabilidad_equipos (
    id SERIAL PRIMARY KEY,
    cliente_instalacion TEXT,
    fecha DATE,
    hora TIME,
    sitio TEXT,
    inventario JSONB,
    tecnico_mantenimiento TEXT,
    firma_tecnico TEXT,
    supervisor_seguridad TEXT,
    firma_supervisor TEXT,
    submitted_by_email TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    company_id INTEGER,
    customer_company_id INTEGER,
    id_propiedad INTEGER,
    latitude NUMERIC,
    longitude NUMERIC,
    location_accuracy NUMERIC,
    submitter_timezone TEXT,
    FOREIGN KEY (company_id) REFERENCES companies(id),
    FOREIGN KEY (customer_company_id) REFERENCES customer_companies(id),
    FOREIGN KEY (id_propiedad) REFERENCES propiedades(id_propiedad)
);

CREATE TABLE IF NOT EXISTS asignaciones_hallazgo (
    id SERIAL PRIMARY KEY,
    form_type TEXT,
    record_id INTEGER,
    asignado_a INTEGER,
    asignado_por TEXT,
    fecha_limite DATE,
    nota TEXT,
    estado TEXT DEFAULT 'Asignado',
    company_id INTEGER,
    creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (company_id) REFERENCES companies(id),
    FOREIGN KEY (asignado_a) REFERENCES users(id)
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_users_company_id ON users(company_id);
CREATE INDEX IF NOT EXISTS idx_authorized_emails_company_id ON authorized_emails(company_id);
CREATE INDEX IF NOT EXISTS idx_customer_companies_company_id ON customer_companies(company_id);
CREATE INDEX IF NOT EXISTS idx_propiedades_customer_company_id ON propiedades(customer_company_id);
CREATE INDEX IF NOT EXISTS idx_reportes_incidentes_company_id ON reportes_incidentes(company_id);

COMMIT;
